### ISSUE TITLE
Doesn't work on v1.7.x

### ISSUE THREAD

**Issue by jiayiyaij** [NodeBB/nodebb-rewards-essentials#12]
Not working at all when added trigger for "Post Count" and ">= 1" and "Award Reputation"

**Comment by wrapperband** [comment]
This issue is causing a security issue with the forum we run and lots of unnecessary extra work for moderators. Could it be given a high priority somehow? If so how?

Does this need a fix in NodeBB? is there an alternate code we could use? Any ideas what might be causing the issue (update to interface?) so we might help fix the issue ....

**Comment by psychobunny** [comment]
@wrapperband your issue seems different from OP's, can you provide more information in a new issue please?
